### ISSUE TITLE
Allow options for any property

### ISSUE THREAD

**Issue by paavo** [Sebobo/Shel.Neos.Schema#1]
Properties `options` should allow anything

```
properties:
  text:
    options:
      silhouette: 'vendor.text.block'
```
