### ISSUE TITLE
New properties missing

### ISSUE THREAD

**Issue by simonschaufi** [Sebobo/Shel.Neos.Schema#21]
Neos 8.0 introduced new properties:

```yaml

'Neos.Demo:Content.Text':
  ui:
    previewIcon: 'resource://Neos.Demo/Images/customIcon.svg'
    previewIconSize: '3x'
```

Please add them to the schema!
