### ISSUE TITLE
childNodes no camelCase allowed

### ISSUE THREAD

**Issue by baschny** [Sebobo/Shel.Neos.Schema#26]
In such a thing:
```
'MyNodeType':
  childNodes:
    leftItem:
      type: 'MyNodeType.Item'
    centerItem:
      type: 'MyNodeType.Item'
    rightItem:
      type: 'MyNodeType.Item'
```
The `childNodes` items are using camel case (as explained also in the docs - https://neos.readthedocs.io/en/stable/References/NodeTypeDefinition.html) but your schema prints out:

```
❌ DistributionPackages/XXX.yaml is invalid [
  {
    instancePath: '/MyNodeType/childNodes',
    schemaPath: '#/additionalProperties/properties/childNodes/propertyNames/pattern',
    keyword: 'pattern',
    params: { pattern: '^[a-z0-9\\-]+$' },
    message: 'must match pattern "^[a-z0-9\\-]+$"',
    propertyName: 'leftItem'
  },
  {
    instancePath: '/MyNodeType/childNodes',
    schemaPath: '#/additionalProperties/properties/childNodes/propertyNames',
    keyword: 'propertyNames',
    params: { propertyName: 'leftItem' },
    message: 'property name must be valid'
  }
]
```

The regexp here (https://github.com/Sebobo/Shel.Neos.Schema/blob/main/NodeTypes.Schema.json#L1451) probably needs to also include `A-Z` upper case chars?
